name: Run IP Generator Script

on:
  schedule:
    - cron: "0 0 25 * *" # Run on the 25th of every month at 00:00 UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Ensure wget is installed
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y wget

      # Set execute permission for the script
      - name: Make Script Executable
        run: chmod +x ./ip-generator.sh

      # Run the script for "IR"
      - name: Run the Script for IR
        run: ./ip-generator.sh IR

      # Verify Output Files
      - name: Verify Output Files
        run: test -f IR_ip_prefixes.txt && test -f IR_address_list.rsc

      # Commit and push changes back to the repository
      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add IR_ip_prefixes.txt IR_address_list.rsc
          git diff --cached --quiet || git commit -m "Update generated files for IR"
          git push

      # Archive the generated files (optional)
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Generated-Files
          path: |
            IR_ip_prefixes.txt
            IR_address_list.rsc
          retention-days: 30
